name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

# Autoriser le jeton GITHUB_TOKEN à déployer sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permet d'éviter les déploiements concurrents
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Build de l'application Angular
        run: npm run build -- --base-href=/Ing3-DevOps-TP3-linting/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/Ing3-DevOps-TP3-linting/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
